In [1]:
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

In [14]:
options= Options()
options.add_argument("--headless")
options.add_argument("--disable-gpu")
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=options)

url = "https://www.flipkart.com/search?q=laptops&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=17"
driver.get(url)

In [15]:
lap_names = []
lap_price = []
category = []
lap_rat = []
tot_rat = []

In [16]:
num_pages =10

In [17]:
for page in range(num_pages):
  time.sleep(55) #time interval btwn each pages
  content = driver.page_source
  soup = BeautifulSoup(content , 'html.parser') # reading the page source
  laptops = soup.find_all('div',class_ ="cPHDOP col-12-12") # all products
  for i in laptops :
    names = i.find('div',class_="KzDlHZ")
    if names:
      lap_names.append(names.get_text(strip = True))
    else :
      lap_names.append('N/A')
    prices = i.find('div',class_="Nx9bqj _4b5DiR")
    if prices:
      lap_price.append(prices.get_text(strip=True))
    else:
      lap_price.append("N/A")
    rating=i.find('div',class_='XQDdHH')
    if rating:
      lap_rat.append(rating.get_text(strip=True))
    else:
      lap_rat.append('N/A')
    total_rating=i.find('span',class_='Wphh3N')
    if total_rating:
      tot_rat.append(total_rating.get_text(strip=True))
    else:
      tot_rat.append('N/A')
    category.append('Laptop')
  try:
    nxt_button = driver.find_element("xpath",'//a[@class="_9QVEpD"]') #identify or locate the image
    nxt_button.click()
  except Exception as e:
    print(e)
    break
driver.quit()

data = {"Laptop_name ":lap_names,
        "Laptop_price": lap_price,'Rating':lap_rat,'Total Ratings':tot_rat,'Category':category}
df = pd.DataFrame(data)
df

,Laptop_name,Laptop_price,Rating,Total Ratings,Category
0,N/A,N/A,N/A,N/A,Laptop
1,N/A,N/A,N/A,N/A,Laptop
2,HP 255 G9 AMD Ryzen 3 Dual Core 3250 - (8 GB/5...,"₹27,350",4.1,"1,480 Ratings&106 Reviews",Laptop
3,DELL Inspiron 3530 Intel Core i3 13th Gen N305...,"₹34,990",N/A,N/A,Laptop
4,HP MSO 2024 Intel Core i5 13th Gen 1334U - (16...,"₹54,490",4.1,297 Ratings&11 Reviews,Laptop
...,...,...,...,...,...
295,HP Pavilion Intel Core Ultra 5 125U - (16 GB/1...,"₹66,990",4.4,217 Ratings&16 Reviews,Laptop
296,N/A,N/A,N/A,N/A,Laptop
297,N/A,N/A,N/A,N/A,Laptop
298,N/A,N/A,4.3,N/A,Laptop
299,N/A,N/A,N/A,N/A,Laptop

In [19]:
df.to_csv("laptops_Capstone.csv",index=False)

In [ ]:
df.to_excel("laptops_Capstone.xlsx",index=False)